name: video_player_swift_example
description: Demonstrates how to use the video_player_swift plugin.

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  video_player_swift:
    path: ../

  cupertino_icons: ^1.0.2
  video_player_platform_interface: ^6.2.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
