name: video_player_swift
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^12.0.0

flutter:
  plugin:
    platforms:
      macos:
        dartPluginClass: SwiftVideoPlayer
        pluginClass: VideoPlayerPlugin
